#!/bin/bash
git clone git@github.com:UCLALibrary/ansible_uclalib_configs.git ansibleroot
git clone git@github.com:UCLALibrary/ansible_uclalib_role_common.git ansibleroot/roles/uclalib_role_common
git clone git@github.com:UCLALibrary/ansible_uclalib_role_ndlcinfo.git ansibleroot/roles/uclalib_role_ndlcinfo
git clone git@github.com:UCLALibrary/ansible_uclalib_role_fedoracamel.git ansibleroot/roles/uclalib_role_fedoracamel
git clone git@github.com:UCLALibrary/ansible_uclalib_role_tomcat.git ansibleroot/roles/uclalib_role_tomcat
git clone git@github.com:UCLALibrary/ansible_uclalib_role_iptables.git ansibleroot/roles/uclalib_role_iptables
git clone git@github.com:UCLALibrary/ansible_uclalib_role_haproxy.git ansibleroot/roles/uclalib_role_haproxy
git clone git@github.com:UCLALibrary/ansible_uclalib_role_sinaischolars.git ansibleroot/roles/uclalib_role_sinaischolars
git clone git@github.com:UCLALibrary/ansible_uclalib_role_iiifimages.git ansibleroot/roles/uclalib_role_iiifimages
git clone git@github.com:UCLALibrary/ansible_uclalib_role_karaf.git ansibleroot/roles/uclalib_role_karaf
git clone git@github.com:UCLALibrary/ansible_uclalib_role_travisdeploy.git ansibleroot/roles/uclalib_role_travisdeploy
git clone git@github.com:UCLALibrary/ansible_uclalib_role_fedora4.git ansibleroot/roles/uclalib_role_fedora4
git clone git@github.com:UCLALibrary/ansible_uclalib_role_java.git ansibleroot/roles/uclalib_role_java
git clone git@github.com:UCLALibrary/ansible_uclalib_role_apache.git ansibleroot/roles/uclalib_role_apache
git clone git@github.com:UCLALibrary/ansible_uclalib_role_solr4.git ansibleroot/roles/uclalib_role_solr4
git clone git@github.com:UCLALibrary/ansible_uclalib_role_dataarchivemysql.git ansibleroot/roles/uclalib_role_dataarchivemysql
git clone git@github.com:UCLALibrary/ansible_uclalib_role_cifsmount.git ansibleroot/roles/uclalib_role_cifsmount
git clone git@github.com:UCLALibrary/ansible_uclalib_role_awscli.git ansibleroot/roles/uclalib_role_awscli
git clone git@github.com:UCLALibrary/ansible_uclalib_role_epel.git ansibleroot/roles/uclalib_role_epel
git clone git@github.com:UCLALibrary/ansible_uclalib_role_nfsmount.git ansibleroot/roles/uclalib_role_nfsmount
git clone git@github.com:UCLALibrary/ansible_uclalib_role_webservices.git ansibleroot/roles/uclalib_role_webservices
git clone git@github.com:UCLALibrary/ansible_uclalib_role_dspace.git ansibleroot/roles/uclalib_role_dspace
git clone git@github.com:UCLALibrary/ansible_uclalib_role_clamav.git ansibleroot/roles/uclalib_role_clamav
git clone git@github.com:UCLALibrary/ansible_uclalib_custom_facts.git ansibleroot/roles/uclalib_custom_facts
git clone git@github.com:UCLALibrary/ansible_uclalib_role_vim.git ansibleroot/roles/uclalib_role_vim
git clone git@github.com:UCLALibrary/ansible_uclalib_role_users.git ansibleroot/roles/uclalib_role_users
git clone git@github.com:UCLALibrary/ansible_uclalib_role_git.git ansibleroot/roles/uclalib_role_git
git clone git@github.com:UCLALibrary/ansible_uclalib_role_java_ant.git ansibleroot/roles/uclalib_role_java_ant
git clone git@github.com:UCLALibrary/ansible_uclalib_role_java_maven.git ansibleroot/roles/uclalib_role_java_maven
git clone git@github.com:UCLALibrary/ansible_uclalib_role_ntp.git ansibleroot/roles/uclalib_role_ntp
git clone git@github.com:UCLALibrary/ansible_uclalib_role_autofs.git ansibleroot/roles/uclalib_role_autofs
git clone git@github.com:UCLALibrary/uclalib_role_openldap.git ansibleroot/roles/uclalib_role_openldap
git clone git@github.com:UCLALibrary/uclalib_role_kerberos.git ansibleroot/roles/uclalib_role_kerberos
git clone git@github.com:UCLALibrary/ansible_uclalib_plays.git ansibleroot/plays